### ISSUE TITLE
ckan-dgp xlsx/geojson processing error: Field can't cast value for type

### ISSUE THREAD

**Issue by OriHoch** [hasadna/datacity-k8s#214]
reproduction steps:

* upload csv file: https://jerusalem.datacity.org.il/dataset/urban-renewal-38/resource/a0104730-30d0-4a4e-b67f-ab4f5e699674
* run the dgp task for xlsx or geojson processing of the relevant instance (or wait 1 hour until it runs)

expected:

* xlsx/geojson resource added to the dataset

actual:

* error in the relevant ckan-dgp task log
* same error occurs for both geojson and xlsx
```
[2021-05-03 11:03:40,579] {logging_mixin.py:112} INFO - Starting xlsx processing (JERUSALEM > urban-renewal-38 > _התחדשות עירונית תמ_א 38 a0104730-30d0-4a4e-b67f-ab4f5e699674)
[2021-05-03 11:03:40,579] {logging_mixin.py:112} INFO - Processing resource...
[2021-05-03 11:03:45,144] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2021-05-03 11:03:45,144] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.7/site-packages/dataflows/base/schema_validator.py", line 65, in schema_validator
    row[field.name] = field.cast_value(row.get(field.name))
[2021-05-03 11:03:45,144] {logging_mixin.py:112} WARNING -   File "/usr/local/lib/python3.7/site-packages/tableschema/field.py", line 170, in cast_value
    ).format(field=self, value=value))
[2021-05-03 11:03:45,144] {logging_mixin.py:112} WARNING - datapackage.exceptions.CastError: Field "תוספת יחד" can't cast value "1.5" for type "integer" with format "default"
```

**Comment by OriHoch** [comment]
error is from our csv processing which guessed a column type to be integer, but one of the values was actually a float.

will fix it so that it doesn't do automatic guessing of field types and just assumes all values are strings

estimate: 1-2 hours

**Comment by niryariv** [comment]
>estimate: 1-2 hours

approved, please implement

**Comment by OriHoch** [comment]
done, deployed, re-ran the tasks, geojson and xlsx files now appear in the dataset
